// Code generated by MockGen. DO NOT EDIT.
// Source: domain/gambler/gambler.interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	notification "github.com/TaApostado/common/notification"
	gomock "github.com/golang/mock/gomock"
)

// MockIGambler is a mock of IGambler interface.
type MockIGambler struct {
	ctrl     *gomock.Controller
	recorder *MockIGamblerMockRecorder
}

// MockIGamblerMockRecorder is the mock recorder for MockIGambler.
type MockIGamblerMockRecorder struct {
	mock *MockIGambler
}

// NewMockIGambler creates a new mock instance.
func NewMockIGambler(ctrl *gomock.Controller) *MockIGambler {
	mock := &MockIGambler{ctrl: ctrl}
	mock.recorder = &MockIGamblerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGambler) EXPECT() *MockIGamblerMockRecorder {
	return m.recorder
}

// Credits mocks base method.
func (m *MockIGambler) Credits() float32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credits")
	ret0, _ := ret[0].(float32)
	return ret0
}

// Credits indicates an expected call of Credits.
func (mr *MockIGamblerMockRecorder) Credits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credits", reflect.TypeOf((*MockIGambler)(nil).Credits))
}

// Deposit mocks base method.
func (m *MockIGambler) Deposit(arg0 float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deposit indicates an expected call of Deposit.
func (mr *MockIGamblerMockRecorder) Deposit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockIGambler)(nil).Deposit), arg0)
}

// Id mocks base method.
func (m *MockIGambler) Id() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(string)
	return ret0
}

// Id indicates an expected call of Id.
func (mr *MockIGamblerMockRecorder) Id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockIGambler)(nil).Id))
}

// Notificator mocks base method.
func (m *MockIGambler) Notificator() notification.INotificator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notificator")
	ret0, _ := ret[0].(notification.INotificator)
	return ret0
}

// Notificator indicates an expected call of Notificator.
func (mr *MockIGamblerMockRecorder) Notificator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notificator", reflect.TypeOf((*MockIGambler)(nil).Notificator))
}

// Withdraw mocks base method.
func (m *MockIGambler) Withdraw(arg0 float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockIGamblerMockRecorder) Withdraw(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockIGambler)(nil).Withdraw), arg0)
}
